apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ybclusters.yugabyte.com
spec:
  group: yugabyte.com
  names:
    kind: YBCluster
    listKind: YBClusterList
    plural: ybclusters
    singular: ybcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              properties:
                pullPolicy:
                  type: string
                repository:
                  type: string
                tag:
                  type: string
              type: object
            master:
              properties:
                enableLoadBalancer:
                  type: boolean
                gflags:
                  items:
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    type: object
                  minItems: 1
                  type: array
                masterRPCPort:
                  format: int32
                  minimum: 1
                  type: integer
                masterUIPort:
                  format: int32
                  minimum: 1
                  type: integer
                podManagementPolicy:
                  type: string
                replicas:
                  format: int32
                  minimum: 1
                  type: integer
                resources:
                  type: object
                storage:
                  properties:
                    count:
                      format: int32
                      minimum: 1
                      type: integer
                    size:
                      pattern: ^[0-9]{1,4}[MGT][IBib]$
                      type: string
                    storageClass:
                      type: string
                  type: object
              type: object
            replicationFactor:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int32
              minimum: 1
              type: integer
            tls:
              properties:
                enabled:
                  type: boolean
                rootCA:
                  properties:
                    cert:
                      type: string
                    key:
                      type: string
                  type: object
              type: object
            tserver:
              properties:
                enableLoadBalancer:
                  type: boolean
                gflags:
                  items:
                    properties:
                      key:
                        type: string
                      value:
                        type: string
                    type: object
                  minItems: 1
                  type: array
                podManagementPolicy:
                  type: string
                replicas:
                  format: int32
                  minimum: 1
                  type: integer
                resources:
                  type: object
                storage:
                  properties:
                    count:
                      format: int32
                      minimum: 1
                      type: integer
                    size:
                      pattern: ^[0-9]{1,4}[MGT][IBib]$
                      type: string
                    storageClass:
                      type: string
                  type: object
                tserverRPCPort:
                  format: int32
                  minimum: 1
                  type: integer
                tserverUIPort:
                  format: int32
                  minimum: 1
                  type: integer
                ycqlPort:
                  format: int32
                  minimum: 1
                  type: integer
                yedisPort:
                  format: int32
                  minimum: 1
                  type: integer
                ysqlPort:
                  format: int32
                  minimum: 1
                  type: integer
              type: object
          type: object
        status:
          properties:
            dataMoveChangeTime:
              format: date-time
              type: string
            dataMoveCond:
              description: 'TODO(bhavin192): remove this once we use Conditions TODO(bhavin192):
                should this have omitempty'
              type: string
            masterReplicas:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              format: int64
              type: integer
            tSScaleDownChangeTime:
              format: date-time
              type: string
            tServerScaleDownCond:
              type: string
            tserverReplicas:
              format: int64
              type: integer
          required:
          - masterReplicas
          - tserverReplicas
          - dataMoveCond
          - dataMoveChangeTime
          - tServerScaleDownCond
          - tSScaleDownChangeTime
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
